project_name: SubTUI

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

    binary: subtui
    
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - repository:
      owner: MattiaPun
      name: homebrew-subtui
    directory: Formula

    homepage: https://github.com/MattiaPun/SubTUI
    description: "A Subsonic TUI Client"
    license: "MIT"

    commit_author:
      name: MattiaPun
      email: mattia@punjwani.pm
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    dependencies:
      - name: mpv

nfpms:
  - id: packages
    package_name: subtui
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    
    homepage: https://github.com/MattiaPun/SubTUI
    maintainer: Mattia Pun <mattia@punjwani.pm>
    vendor: MattiaPun
    description: "A Subsonic TUI Client"
    license: MIT
    
    formats:
      - rpm
      - deb 
    dependencies:
      - mpv
      
    bindir: /usr/bin
